### PR TITLE
fix #301: QueuedChannel futures don't wait forever when delegates throw

### LINKED ISSUE #301: QueuedChannel result listeners can block forever when exceptions are thrown from delegates
## What happened?
Channels aren't supposed to throw. We have a backstop against bugs when they do, however the QueuedChannel needs to wrap delegates with a similar backstop, otherwise failures are not propagated to callers.

## What did you want to happen?

All futures should be completed eventually.

### PR DESCRIPTION
**Pull request by carterkozak**
## Before this PR
futures could never be completed.

## After this PR
==COMMIT_MSG==
QueuedChannel futures don't wait forever when delegates throw
==COMMIT_MSG==

### CODE REVIEW

File: dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java [hunk 1]
```diff
@@ -114,6 +115,26 @@ public void testQueuedRequestExecutedOnNextSubmission() {
...
 
+    @Test
+    public void testQueuedRequestExecutedOnNextSubmission_throws() throws ExecutionException, InterruptedException {
+        Request queuedRequest = Mockito.mock(Request.class);
+        when(delegate.maybeExecute(endpoint, queuedRequest)).thenReturn(Optional.empty());
+        ListenableFuture<Response> queuedFuture = queuedChannel.execute(endpoint, queuedRequest);
+        verify(delegate, times(2)).maybeExecute(endpoint, queuedRequest);
+        assertThat(queuedFuture).isNotDone();
+
+        futureResponse.set(mockResponse);
```
Comment (ferozco) [inline dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java:128]: I would find it helpful to leave little comments explaining what you expect to be happening since just reading the test case requires tracing through the queuedChannel impl to understand why this is testing what it says it is

Comment (carterkozak) [reply dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java:128]: good call, updated.

**Comment by ferozco** [comment]
👍
