### PR TITLE
fix #386: Limit connections-per-host using a LimitedChannel

### LINKED ISSUE #386: Replace client implementation per-host connection limits with a LimitedChannel
## What happened?

Each client configures its own connection pool. These can be unlimited to avoid unexpected internal blocking/queueing in favor of a limited channel that applies to all channels.

## What did you want to happen?

The default per host should be 256 connections to match cjr-okhttp.

### PR DESCRIPTION
**Pull request by carterkozak**
## After this PR
==COMMIT_MSG==
Limit connections-per-host using a LimitedChannel
==COMMIT_MSG==

## Possible downsides?
Unlike the remoting-okhttp implementation there's no static global state, so two unique channels created for the same target will each get 256 requests.

### CODE REVIEW

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+    }
+
+    @Override
+    public Optional<ListenableFuture<Response>> maybeExecute(Endpoint endpoint, Request request) {
+        // Doesn't check for integer underflow, we don't have enough threads for that to be possible
+        if (availablePermits.decrementAndGet() < 0) {
+            availablePermits.incrementAndGet();
+            if (log.isDebugEnabled()) {
+                log.debug(
+                        "Permits have been exhausted",
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: permits as a safearg too?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+    FixedLimitedChannel(LimitedChannel delegate, int permits) {
+        this.delegate = delegate;
+        this.availablePermits = new AtomicInteger(permits);
+    }
+
+    @Override
+    public Optional<ListenableFuture<Response>> maybeExecute(Endpoint endpoint, Request request) {
+        // Doesn't check for integer overflow, we don't have enough threads for that to occur.
+        if (availablePermits.decrementAndGet() < 0) {
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: could we hoist this to a variable just to emphasise that it's stateful and affects both the if body and the fallthrough?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+import org.slf4j.LoggerFactory;
+
+/**
+ * Channel with a fixed number of available permits. This can be used to enforce a per-route request limit.
+ */
+final class FixedLimitedChannel implements LimitedChannel {
+    private static final Logger log = LoggerFactory.getLogger(FixedLimitedChannel.class);
+
+    private final LimitedChannel delegate;
+    private final AtomicInteger availablePermits;
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: Somehow my brain prefers the inversion of this, where this number starts at zero and counts the number of active requests?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+            availablePermits.incrementAndGet();
+            if (log.isDebugEnabled()) {
+                log.debug(
+                        "Permits have been exhausted",
+                        SafeArg.of("service", endpoint.serviceName()),
+                        SafeArg.of("endpoint", endpoint.endpointName()));
+            }
+            return Optional.empty();
+        }
+        boolean resetPermit = true;
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: what about flipping this round so that it's named `delegateRejectedRequest = false`, and then after we get an optional.empty we set it to true?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java (hunk 3 above)
Comment (iamdanfox) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: Just a thought - do you think a LongAdder would reduce contention and increase throughput here? I'm just thinking if all the witchcraft worker threads in a server are constantly blasting though these FixedLimitedChannels and there are two atomicinteger writes per call to maybeExecute, perhaps making the single read a bit more expensive by calling `LongAdder#sum()` would be worth it?

Quite possibly over-optimizing, just wanted to throw the idea out there

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+        try {
+            Optional<ListenableFuture<Response>> result = delegate.maybeExecute(endpoint, request);
+            if (result.isPresent()) {
+                result.get().addListener(availablePermits::incrementAndGet, MoreExecutors.directExecutor());
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: do method references like this allocate each time?

**Comment by iamdanfox** [comment]
> so two unique channels created for the same target will each get 256 requests.

We can always stick a cache in WC to prevent people from creating endless clients pointing to the same thing if we have to!

File: dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java [hunk 6]
```diff
@@ -49,6 +48,7 @@ public static Channel create(
                 .map(channel -> new TracedChannel(channel, "Dialogue-http-request"))
                 .map(ContentDecodingChannel::new)
                 .map(concurrencyLimiter(config))
+                .map(channel -> new FixedLimitedChannel(channel, MAX_REQUESTS_PER_CHANNEL))
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java:51]: would you mind dropping this into the simulator Strategy enum too please?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java (hunk 3 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: LongAdder doesn't provide any concurrency guarantees, I believe reading the value is more expensive though writing is cheap. It works well for things like counters/meters because they have orders of magnitude more writes than reads, and the value doesn't need to be precise.

There's always AtomicIntegerFieldUpdater, but it performs similarly to AtomicInteger with lower allocation overhead for creation, we could use it if we wanted to optimize around fitting the entire channel chain into a cache line... but that's likely a bit too far.

File: dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java (hunk 6 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java:51]: good call. Perhaps we should overload channels with a method that takes clocks so we can keep them in sync?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java (hunk 5 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: Yep (mostly, I think it's possible to get it inlined, but that takes a while and is fiddly). I'll update :-)

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java (hunk 4 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: That fails if the delegate channel throws. I should add a test for that case ;-)

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java (hunk 1 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: good call

File: dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java (hunk 6 above)
Comment (iamdanfox) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/Channels.java:51]: Yep I think my facade is gonna include a clock

File: dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java (hunk 4 above)
Comment (iamdanfox) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: On first read I was trying to figure out what fancy logic the ‘resetPermits’ thing was doing, like was it a backstop or something.

What if we called it “resetOptimisticallyConsumedPermit” or something?

Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/FixedLimitedChannel.java]: 👍

**Review by iamdanfox — APPROVED** [review]
Out of curiosity, does this change any of the simulations? Or did nothing get to 256 requests/host?

**Comment by carterkozak** [comment]
I don't think any of them hit concurrent 256 requests/host
