### PR TITLE
fix #391: QueuedChannel correctly propagates cancellation

### LINKED ISSUE #391: QueuedChannel queued requests fail to propagate cancellation
## What happened?

the returned future may be cancelled but it has no impact on execution of the queued work.

## What did you want to happen?

Cancellation should be respected

### PR DESCRIPTION
**Pull request by carterkozak**
==COMMIT_MSG==
QueuedChannel correctly propagates cancellation
==COMMIT_MSG==

### CODE REVIEW

File: dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java [hunk 1]
```diff
@@ -144,16 +144,33 @@ private boolean scheduleNextTask() {
...
-            if (response.isPresent()) {
+            if (maybeResponse.isPresent()) {
+                ListenableFuture<Response> response = maybeResponse.get();
                 components.span().complete();
                 numRunningRequests.incrementAndGet();
-                response.get().addListener(numRunningRequests::decrementAndGet, DIRECT);
-                Futures.addCallback(response.get(), new ForwardAndSchedule(components.response()), DIRECT);
+                response.addListener(numRunningRequests::decrementAndGet, DIRECT);
+                Futures.addCallback(response, new ForwardAndSchedule(queuedResponse), DIRECT);
+                queuedResponse.addListener(
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java:164]: so this is just saying if a request comes off the queue and gets sent down the delegate pipe, but the user decides to cancel the settablefuture they were holding, then we try and cancel the thing we sent down the delegate chain?

How will our lowest-level layer clients perceive this? does it just set the interrupted flag which we'd then hope something in apache would check?

File: dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java [hunk 2]
```diff
@@ -144,16 +144,33 @@ private boolean scheduleNextTask() {
...
+                        () -> {
+                            if (queuedResponse.isCancelled()) {
+                                // TODO(ckozak): Consider capturing the argument value provided to cancel to propagate
+                                // here.
+                                // Currently cancel(false) will be converted to cancel(true)
+                                response.cancel(true);
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java]: the javadoc on this says `@return {@code false} if the task could not be cancelled, typically because it has already completed normally;`... i wonder if it's worth putting a debug log line in that case? I feel like the timelock folks had so much time debugging cancellations that they'd want every bit of signal they could get

File: dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java (hunk 1 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java:164]: Since we use the blocking channel adapter, the thread running the request is interrupted which may result in the request stopping depending on the point in the lifecycle.

File: dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java (hunk 2 above)
Comment (carterkozak) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/QueuedChannel.java]: good call!

**Review by iamdanfox — APPROVED** [review]

File: dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java [hunk 3]
```diff
@@ -212,18 +215,62 @@ public void emitsQueueCapacityMetrics_whenChannelHasCapacity() {
...
         queuedChannel.execute(endpoint, request);
-        verify(delegate, times(3)).maybeExecute(endpoint, request);
-        futureResponse.set(mockResponse);
+        assertThat(result).isCancelled();
+        verify(delegate, times(1)).maybeExecute(endpoint, request);
         verify(mockResponse, times(1)).close();
     }
 
+    @Test
+    @SuppressWarnings("FutureReturnValueIgnored")
```
Comment (uschi2000) [inline dialogue-core/src/test/java/com/palantir/dialogue/core/QueuedChannelTest.java:240]: nit: can probably add this at class-level?
