### PR TITLE
Minor logging tweaks

### LINKED ISSUE #736: RetryingChannel stacktraces do not contain useful signal for dialogue _users_
## What happened?

In production and in tests, there are tons and tons of this identical stacktrace:

```
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-12 16:04:47,789 INFO [dialogue-blocking-channel-1] com.palantir.dialogue.core.RetryingChannel - Retrying call after failure
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-12 16:04:47,789 INFO [dialogue-blocking-channel-35] com.palantir.dialogue.core.RetryingChannel - Retrying call after failure
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-05-12 16:04:47,801 INFO [dialogue-blocking-channel-19] com.palantir.dialogue.core.RetryingChannel - Retrying call after failure
com.palantir.logsafe.exceptions.SafeRuntimeException: Received retryable response: {status=429}
	at com.palantir.dialogue.core.RetryingChannel.lambda$static$1(RetryingChannel.java:84)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.incrementFailuresAndMaybeRetry(RetryingChannel.java:282)
	at com.palantir.dialogue.core.RetryingChannel$RetryingCallback.handleHttpResponse(RetryingChannel.java:255)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:213)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:202)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:118)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:267)
	at com.palantir.dialogue.core.QueuedChannel$ForwardAndSchedule.onSuccess(QueuedChannel.java:258)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1089)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1174)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:738)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:47)
	at com.palantir.dialogue.blocking.BlockingChannelAdapter$BlockingChannelAdapterChannel$BlockingChannelAdapterTask.run(BlockingChannelAdapter.java:129)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:501)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.palantir.tritium.metrics.TaggedMetricsThreadFactory$InstrumentedTask.run(TaggedMetricsThreadFactory.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

These stacktraces record information that could theoretically be useful to dialogue _maintainers_, but are not useful to users.

## What did you want to happen?

I'd propose turning these off, perhaps unless people have explicitly enabled debug/trace logging for RetryingChannel?

### PR DESCRIPTION
**Pull request by iamdanfox**
fixes https://github.com/palantir/dialogue/issues/736

## Before this PR

Iterating on the IntegrationTest to figure out what's going on with our ConcurrencyLimiters is pretty hard right now, as there are either too many or not enough logs.

(Also I still find RetryingChannel hard to read/refactor - see my [abandoned attempt](https://github.com/palantir/dialogue/pull/730))

## After this PR
==COMMIT_MSG==
RetryingChannel no longer logs stacktraces at info, as these are primarily useful for dialogue maintainers not users. Dialling up logging to debug will still cause call-site stacktraces to be recorded, although this comes with a performance cost.
==COMMIT_MSG==

### CODE REVIEW

File: dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java [hunk 1]
```diff
@@ -334,13 +333,12 @@ private boolean shouldAttemptToRetry(Throwable throwable) {
...
         }
 
-        private void logRetry(long backoffNanoseconds, @Nullable Throwable throwable) {
+        private void infoLogRetry(@Nullable Throwable throwable) {
             if (log.isInfoEnabled()) {
                 log.info(
                         "Retrying call after failure",
                         SafeArg.of("failures", failures),
                         SafeArg.of("maxRetries", maxRetries),
-                        SafeArg.of("backoffMillis", TimeUnit.NANOSECONDS.toMillis(backoffNanoseconds)),
```
Comment (iamdanfox) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/RetryingChannel.java:343]: keeping this plumbed in will require refactoring RetryingChannel a bit more.

File: dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java [hunk 2]
```diff
@@ -106,7 +110,10 @@ void ignore() {
          */
         void dropped() {
             inFlight.decrementAndGet();
-            limit.accumulateAndGet(inFlightSnapshot, LimitUpdater.DROPPED);
+            int newLimit = limit.accumulateAndGet(inFlightSnapshot, LimitUpdater.DROPPED);
+            if (log.isDebugEnabled()) {
+                log.debug("DOWN {}", SafeArg.of("newLimit", newLimit));
```
Comment (ferozco) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: I really wish we could use timber here since it does the defensive level check for you

Comment (iamdanfox) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: Honestly I've actually acclimatised to this `if` pattern in perf-sensitive library code (obviously don't want this all over normal services, but kinda non painful)

Comment (ferozco) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: eh I think it just adds a bunch of noise to the code

File: dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java [hunk 3]
```diff
@@ -115,7 +122,10 @@ void dropped() {
          */
         void success() {
             inFlight.decrementAndGet();
-            limit.accumulateAndGet(inFlightSnapshot, LimitUpdater.SUCCESS);
+            int newLimit = limit.accumulateAndGet(inFlightSnapshot, LimitUpdater.SUCCESS);
+            if (log.isDebugEnabled()) {
+                log.debug("UP {}", SafeArg.of("newLimit", newLimit));
```
Comment (ferozco) [inline dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: Why do we have format characters in these log lines? I thought we had an errorprone rule to discourage you from doing so

Comment (ferozco) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: nit: better message, something like `limit increased.`

Comment (iamdanfox) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: My motivation for this PR is iterating on the SimulationTest to figure out better implementations for the ConcurrencyLimiters. We don't have sls-logging here in open-source land, so without these curly braces I'd just get:

INFO [main] com.palantir.dialogue.core.AimdConcurrencyLimiter - UP
INFO [main] com.palantir.dialogue.core.AimdConcurrencyLimiter - UP
INFO [main] com.palantir.dialogue.core.AimdConcurrencyLimiter - UP
INFO [main] com.palantir.dialogue.core.AimdConcurrencyLimiter - DOWN
INFO [main] com.palantir.dialogue.core.AimdConcurrencyLimiter - UP
INFO [main] com.palantir.dialogue.core.AimdConcurrencyLimiter - DOWN

Which doesn't give me enough useful signal, especially when requests are coming back concurrently so they might jump from 7 -> 9 -> 13 and then down to 6

Comment (ferozco) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: Ok sure, can we only add it to the debug lines then? Its kinda gross to have these unnecessary curlies in info logs we expect to be consumed through sls-logging.

Alternatively, we could open source sls-logging if feel like shaving a yak

Comment (iamdanfox) [reply dialogue-core/src/main/java/com/palantir/dialogue/core/AimdConcurrencyLimiter.java]: The majority of these log lines are debug already, so most people won't see them. The exception are things like `Exhausted {} retries, returning last received response with status {}`, which was already info.

I actually do want to keep the remaining curlies though this concretely helps me build stuff in this repo (and we've had explicit feedback that sls-logging style stuff in oss libraries is unhelpful https://github.com/palantir/dialogue/issues/700).

**Comment by ferozco** [comment]
👍
